import myfunctions as mf

# region datos
# Tupla de categorias
productos_cat = ("lacteos", "bebidas", "frutas", "verduras", "limpieza")
# Diccionario de productos
productos = {
    1: {
        "nombre": "leche entera",
        "marca": "Serenisima",
        "precio": 300,
        "stock": 100,
        "iva": 10.5,
        "categoria": 0,
        "costo": 220,
    },
    2: {
        "nombre": "leche entera",
        "marca": "Las 3 niñas",
        "precio": 280,
        "stock": 80,
        "iva": 10.5,
        "categoria": 0,
        "costo": 200,
    },
    3: {
        "nombre": "yogur natural",
        "marca": "La Serenisima",
        "precio": 200,
        "stock": 50,
        "iva": 10.5,
        "categoria": 0,
        "costo": 150,
    },
    4: {
        "nombre": "queso crema",
        "marca": "La Paulina",
        "precio": 600,
        "stock": 40,
        "iva": 10.5,
        "categoria": 0,
        "costo": 450,
    },
    5: {
        "nombre": "manteca",
        "marca": "Sancor",
        "precio": 450,
        "stock": 30,
        "iva": 10.5,
        "categoria": 0,
        "costo": 320,
    },
    6: {
        "nombre": "queso rallado",
        "marca": "Molfino",
        "precio": 700,
        "stock": 25,
        "iva": 10.5,
        "categoria": 0,
        "costo": 500,
    },
    7: {
        "nombre": "yogur bebible",
        "marca": "Serenisima",
        "precio": 220,
        "stock": 60,
        "iva": 10.5,
        "categoria": 0,
        "costo": 170,
    },
    8: {
        "nombre": "crema de leche",
        "marca": "La Serenisima",
        "precio": 550,
        "stock": 35,
        "iva": 10.5,
        "categoria": 0,
        "costo": 400,
    },
    9: {
        "nombre": "agua mineral",
        "marca": "Villavicencio",
        "precio": 500,
        "stock": 200,
        "iva": 10.5,
        "categoria": 1,
        "costo": 350,
    },
    10: {
        "nombre": "refresco cola",
        "marca": "Coca Cola",
        "precio": 1200,
        "stock": 150,
        "iva": 21,
        "categoria": 1,
        "costo": 900,
    },
    11: {
        "nombre": "refresco limón",
        "marca": "Pepsi",
        "precio": 1100,
        "stock": 120,
        "iva": 21,
        "categoria": 1,
        "costo": 850,
    },
    12: {
        "nombre": "jugo de naranja",
        "marca": "Cepita",
        "precio": 950,
        "stock": 100,
        "iva": 21,
        "categoria": 1,
        "costo": 700,
    },
    13: {
        "nombre": "jugo de manzana",
        "marca": "Cepita",
        "precio": 950,
        "stock": 100,
        "iva": 21,
        "categoria": 1,
        "costo": 700,
    },
    14: {
        "nombre": "bebida energizante",
        "marca": "Red Bull",
        "precio": 3500,
        "stock": 50,
        "iva": 21,
        "categoria": 1,
        "costo": 2500,
    },
    15: {
        "nombre": "té frío sabor durazno",
        "marca": "Lipton",
        "precio": 1200,
        "stock": 80,
        "iva": 21,
        "categoria": 1,
        "costo": 900,
    },
    16: {
        "nombre": "agua con gas",
        "marca": "Eco de los Andes",
        "precio": 600,
        "stock": 180,
        "iva": 10.5,
        "categoria": 1,
        "costo": 400,
    },
    17: {
        "nombre": "manzana",
        "marca": "N/A",
        "precio": 200,
        "stock": 150,
        "iva": 0,
        "categoria": 2,
        "costo": 120,
    },
    18: {
        "nombre": "banana",
        "marca": "N/A",
        "precio": 180,
        "stock": 180,
        "iva": 0,
        "categoria": 2,
        "costo": 100,
    },
    19: {
        "nombre": "naranja",
        "marca": "N/A",
        "precio": 220,
        "stock": 140,
        "iva": 0,
        "categoria": 2,
        "costo": 150,
    },
    20: {
        "nombre": "pera",
        "marca": "N/A",
        "precio": 210,
        "stock": 130,
        "iva": 0,
        "categoria": 2,
        "costo": 140,
    },
    21: {
        "nombre": "uva",
        "marca": "N/A",
        "precio": 250,
        "stock": 120,
        "iva": 0,
        "categoria": 2,
        "costo": 180,
    },
    22: {
        "nombre": "kiwi",
        "marca": "N/A",
        "precio": 300,
        "stock": 90,
        "iva": 0,
        "categoria": 2,
        "costo": 220,
    },
    23: {
        "nombre": "frutilla",
        "marca": "N/A",
        "precio": 350,
        "stock": 80,
        "iva": 0,
        "categoria": 2,
        "costo": 280,
    },
    24: {
        "nombre": "melon",
        "marca": "N/A",
        "precio": 400,
        "stock": 70,
        "iva": 0,
        "categoria": 2,
        "costo": 320,
    },
    25: {
        "nombre": "sandía",
        "marca": "N/A",
        "precio": 450,
        "stock": 60,
        "iva": 0,
        "categoria": 2,
        "costo": 350,
    },
    26: {
        "nombre": "lechuga",
        "marca": "N/A",
        "precio": 150,
        "stock": 100,
        "iva": 0,
        "categoria": 3,
        "costo": 100,
    },
    27: {
        "nombre": "tomate",
        "marca": "N/A",
        "precio": 200,
        "stock": 120,
        "iva": 0,
        "categoria": 3,
        "costo": 140,
    },
    28: {
        "nombre": "zanahoria",
        "marca": "N/A",
        "precio": 180,
        "stock": 90,
        "iva": 0,
        "categoria": 3,
        "costo": 120,
    },
    29: {
        "nombre": "papa",
        "marca": "N/A",
        "precio": 120,
        "stock": 200,
        "iva": 0,
        "categoria": 3,
        "costo": 90,
    },
    30: {
        "nombre": "cebolla",
        "marca": "N/A",
        "precio": 160,
        "stock": 150,
        "iva": 0,
        "categoria": 3,
        "costo": 120,
    },
    31: {
        "nombre": "espinaca",
        "marca": "N/A",
        "precio": 170,
        "stock": 80,
        "iva": 0,
        "categoria": 3,
        "costo": 130,
    },
    32: {
        "nombre": "morron rojo",
        "marca": "N/A",
        "precio": 250,
        "stock": 70,
        "iva": 0,
        "categoria": 3,
        "costo": 180,
    },
    33: {
        "nombre": "calabaza",
        "marca": "N/A",
        "precio": 300,
        "stock": 60,
        "iva": 0,
        "categoria": 3,
        "costo": 220,
    },
    34: {
        "nombre": "detergente líquido",
        "marca": "Ala",
        "precio": 700,
        "stock": 100,
        "iva": 21,
        "categoria": 4,
        "costo": 500,
    },
    35: {
        "nombre": "lavandina",
        "marca": "Ayudín",
        "precio": 350,
        "stock": 80,
        "iva": 21,
        "categoria": 4,
        "costo": 250,
    },
    36: {
        "nombre": "limpiador multiuso",
        "marca": "Cif",
        "precio": 500,
        "stock": 60,
        "iva": 21,
        "categoria": 4,
        "costo": 350,
    },
    37: {
        "nombre": "esponjas",
        "marca": "Scotch-Brite",
        "precio": 200,
        "stock": 120,
        "iva": 21,
        "categoria": 4,
        "costo": 150,
    },
    38: {
        "nombre": "pañales de papel",
        "marca": "Huggies",
        "precio": 1500,
        "stock": 50,
        "iva": 21,
        "categoria": 4,
        "costo": 1100,
    },
    39: {
        "nombre": "guantes de limpieza",
        "marca": "N/A",
        "precio": 300,
        "stock": 70,
        "iva": 21,
        "categoria": 4,
        "costo": 200,
    },
    40: {
        "nombre": "ambientador spray",
        "marca": "Glade",
        "precio": 450,
        "stock": 60,
        "iva": 21,
        "categoria": 4,
        "costo": 320,
    },
}
# Diccionario de empleados
empleados = {
    1: {
        "dni": 12345678,
        "nombre": "Juan",
        "apellido": "Perez",
        "claves": 1,
        "empleados_turno": 1,
        "empleados_rol": 1,
    },
    2: {
        "dni": 34567892,
        "nombre": "Ana",
        "apellido": "Gonzales",
        "claves": 2,
        "empleados_turno": 2,
        "empleados_rol": 1,
    },
    3: {
        "dni": 33345421,
        "nombre": "Ramón",
        "apellido": "Diaz",
        "claves": 3,
        "empleados_turno": 3,
        "empleados_rol": 1,
    },
    4: {
        "dni": 34345532,
        "nombre": "Micaela",
        "apellido": "Martinez",
        "claves": 4,
        "empleados_turno": 1,
        "empleados_rol": 2,
    },
    5: {
        "dni": 12345222,
        "nombre": "Educardo",
        "apellido": "Ramirez",
        "claves": 5,
        "empleados_turno": 1,
        "empleados_rol": 2,
    },
    6: {
        "dni": 34345442,
        "nombre": "Juan",
        "apellido": "Pérez",
        "claves": 6,
        "empleados_turno": 2,
        "empleados_rol": 2,
    },
    7: {
        "dni": 23234545,
        "nombre": "Lucía",
        "apellido": "Gómez",
        "claves": 7,
        "empleados_turno": 2,
        "empleados_rol": 2,
    },
    8: {
        "dni": 234554324,
        "nombre": "Diego",
        "apellido": "Fernández",
        "claves": 8,
        "empleados_turno": 3,
        "empleados_rol": 3,
    },
    9: {
        "dni": 12325453,
        "nombre": "Sofía",
        "apellido": "Vargas",
        "claves": 9,
        "empleados_turno": 3,
        "empleados_rol": 3,
    },
}
# Pin de los empleados
claves = {
    1: {"pin": 1234},
    2: {"pin": 4424},
    3: {"pin": 2345},
    4: {"pin": 2432},
    5: {"pin": 3321},
    6: {"pin": 1132},
    7: {"pin": 3342},
    8: {"pin": 3452},
    9: {"pin": 5621},
}
# Rol con sueldo
empleados_rol = {
    1: {"nombre": "Gerente", "sueldo": 1500000},
    2: {"nombre": "Cajero", "sueldo": 500000},
    3: {"nombre": "Repositor", "sueldo": 350000},
}
# Tupla de turnos
empleados_turno = ("Mañana", "Tarde", "Noche")
# Diccionario de ventas
ventas = {}
# Diccionario de notificaciones por baja de stock
notificaciones = {}
# Diccionario de productos relacionados con una venta
ventas_productos = {}
# endregion


# Funcion principal
def main():
    usuario = 0
    while usuario == 0:
        mf.cls()
        usuario = mf.login()
        if usuario > 0:
            codigo_rol = mf.obtener_codigo_rol(usuario)
            mf.mostrar_menu(codigo_rol)
            op = mf.solicitar_operacion()
            mf.cls()
            usuario = mf.procesar_operacion(op, codigo_rol, usuario)


if __name__ == "__main__":
    main()
